---
title: "coverage_analysis_SS1example"
output: html_document
date: "2024-10-17"
---

Functions required to create combined dataset (coverage + length information across read types) and create databases for different jobs (main one used here is opt = 'long' as require long format database for scatterplots)
```{r}
combine <- function(file_types, coverm_files, length_file){
  lens <- read.table(length_file, header=FALSE)
  colnames(lens) <- c("contig", "length")
    
  for (i in 1:length(file_types)){
    mid_db <- read.delim(coverm_files[i])
    colnames(mid_db) <- c("contig", paste0(file_types[i]))

    if (i == 1){
      coverdb <- full_join(x = mid_db,
                           y = lens, by="contig")
    }else{
      coverdb <- full_join(x = mid_db, 
                           y = coverdb, by="contig")
    }
  }
  coverdb[is.na(coverdb)] = 0
  coverdb <- coverdb %>%
    mutate(total = rowSums(across(-c("length","contig"))),
           len_bin_kb=cut(length/1000, breaks=c(seq(0, 400, by=20), 500, 1000, seq(2000, max(length)/1000, by=1000))),
           cov_grp=cut(total, breaks=c(seq(0, 50, by=5),
                                       seq(100, 1000, by=50),
                                       max(total))))
  return(coverdb)
}

alt_db <- function(db, opt){
  if (opt == 'box'){
    new_db <- db %>% 
      subset(select = -c(total, len_bin_kb, cov_grp)) %>%
      pivot_longer(cols=-c("contig","length"), 
                   names_to="read_type", values_to="mean_coverage")
  }else if (opt == 'long'){
    new_db <- db %>%
      subset(select = -c(len_bin_kb, cov_grp)) %>%
      pivot_longer(cols=-c("contig","length"), 
                   names_to="read_type", values_to="mean_coverage")
    
  }else if (opt == 'bar'){
    new_db <- db %>% 
      subset(select = -c(total, contig, length, cov_grp)) %>%
      group_by(len_bin_kb) %>% 
      summarise(ONT=mean(ONT), HIFI=mean(HIFI), SR=mean(SR)) %>%
      pivot_longer(cols=-c('len_bin_kb'),
                   names_to="read_type", values_to="mean_coverage")
  }
  return(new_db)
}
```

Function for scatterplot generation (two different plotting options - may require editing of axes depending on dataset)
```{r}
xlen_ycov <- function(db, db_long, title, subtitle, div = 1000, w=TRUE){
  #if div = 1000 (default), get lengths of contigs in kbs
  #if w=TRUE (default), will wrap by read type. If not, will just give total

  #calculating statistics to be printed/used in plots
  ONT_MEAN <- mean(db$ONT)
  ONT_MEDIAN <- median(db$ONT)
  ONT_TEXT <- paste0("Mean(median): ", round(ONT_MEAN, digits=2),
                     ' (', round(ONT_MEDIAN, digits=2), ')')
  HIFI_MEAN <- mean(db$HIFI)
  HIFI_MEDIAN <- median(db$HIFI)
  HIFI_TEXT <- paste0("Mean(median): ", round(HIFI_MEAN, digits=2),
                      ' (', round(HIFI_MEDIAN, digits=2), ')')
  SR_MEAN <- mean(db$SR)
  SR_MEDIAN <- median(db$SR)
  SR_TEXT <- paste0("Mean(median): ", round(SR_MEAN, digits=2),
                    ' (', round(SR_MEDIAN, digits=2), ')')
  VAL_MEAN <- mean(db$total)
  VAL_MEDIAN <- median(db$total)
  VAL_TEXT <- paste0("Mean(median): ", round(VAL_MEAN, digits=2),
                     ' (', round(VAL_MEDIAN, digits=2), ')')
  
  dat_text <- data.frame(label = c(ONT_TEXT, HIFI_TEXT, SR_TEXT, VAL_TEXT),
                         read_type = c("ONT","HIFI", "SR", "total"))
  m <- max(coverdb_long$length)/div
  
  if (w==TRUE){
    p <- ggplot(db_long, aes(x=length/div, y=mean_coverage, colour=read_type)) +
      geom_point(alpha=0.9) +
      geom_text(size=3, colour = "black", data = dat_text, 
              mapping = aes(x = -Inf, y = -Inf, label = label),
              hjust = -1, vjust = -16) +
      theme(legend.position="none") +
      facet_wrap(~read_type)
  } else {
    nex <- db_long[db_long$read_type=='total',]
    p <- ggplot(nex, aes(x=length/div, y=mean_coverage)) +
      geom_point(alpha=0.9, colour ="#8C9A7C") +
      geom_hline(yintercept=30, linetype="dashed", colour="#EB4C42") +
      geom_hline(yintercept=VAL_MEAN, 
             linetype="dashed", colour="#90323D") +
      annotate(geom="text", y=2000, x=1750, colour="#90323D",size=3.7,
           label=paste0("Mean coverage: ", round(VAL_MEAN, digits=2))) +
      geom_hline(yintercept=VAL_MEDIAN, 
             linetype="dashed", colour="#355e3b") +
      annotate(geom="text", y=1000, x=1750, colour="#355e3b",size=3.7,
           label=paste0("Median coverage: ", round(VAL_MEDIAN, digits=2)))
      
  }
  
  p <- p +
    scale_colour_manual(values=c("#F6A600", "#7286A0", "#8DB600", "#CC4E5C")) +
    geom_hline(yintercept=30, linetype="dashed", colour="#2F4F4F") +
    scale_x_continuous(trans = scales::pseudo_log_trans(sigma = 1),
                       breaks=c(0, 10, 25, 50, 100, 250,500, 
                                1000,2500,5000,10000),
                       minor_breaks = NULL) +
    scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 4),
                       breaks = c(0, 5, 10, 20, 30, 100, 1000, 5000), 
                       minor_breaks = NULL) +
    theme(legend.position="none") +
    labs(title=title, subtitle=subtitle) + 
    xlab("Length (kb, log-scale)") + 
    ylab("Mean Coverage (log-scale)")
  
  return(p)
}

```


```{r warning=FALSE}
library(forcats)
library(viridis)
library(ggplot2)
library(reshape)
library(readr)
library(dplyr)
library(scatterpie)
library(tidyr)
library(psych) 

directory = "~/Desktop/quick/cover_data/"
setwd(directory)

file_types = c("HIFI","ONT","SR")
coverm_files = c("SS1_p0filt_SRpol_HIFIcoverm.txt", 
                 "SS1_p0filt_SRpol_ONTcoverm.txt",
                 "SS1_p0filt_SRpol_SRcoverm.txt")
length_file = "SS1_p0filt_SRpol_lengths_fixed.tsv"

SS1p0_coverdb <- combine(file_types, coverm_files, length_file)
SS1p0_coverdb_long <- alt_db(coverdb, opt="long")

coverm_files = c("SS1_p1filt_SRpol_HIFIcoverm.txt", 
                 "SS1_p1filt_SRpol_ONTcoverm.txt",
                 "SS1_p1filt_SRpol_SRcoverm.txt")
length_file = "SS1_p1filt_SRpol_lengths_fixed.tsv"

SS1p1_coverdb <- combine(file_types, coverm_files, length_file)
SS1p1_coverdb_long <- alt_db(coverdb, opt="long")

```

```{r}
t="SS1, purge=0: contig length by coverage plot"
SS1p0_g <- xlen_ycov(SS1p0_coverdb, SS1p0_coverdb_long, title=t, subtitle="Divided by read type", w=TRUE)
SS1p0_gtot <- xlen_ycov(SS1p0_coverdb, SS1p0_coverdb_long, title=t, subtitle="Combined (total) coverage", w=FALSE)
SS1p0_g
SS1p0_gtot
```

```{r}
t="SS1, purge=1: contig length by coverage plot"
SS1p1_g <- xlen_ycov(SS1p1_coverdb, SS1p1_coverdb_long, title=t, subtitle="Divided by read type", w=TRUE)
SS1p1_gtot <- xlen_ycov(SS1p1_coverdb, SS1p1_coverdb_long, title=t, subtitle="Combined (total) coverage", w=FALSE)
SS1p1_g
SS1p1_gtot
```


